# Generated by Django 4.1.7 on 2023-09-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.IntegerField()),
                ('Academic_Performance', models.CharField(max_length=100)),
                ('Attendance', models.IntegerField()),
                ('StudyHabits', models.TextField()),
                ('Goals', models.TextField()),
                ('Learning_Disabilities', models.BooleanField(default=False)),
                ('Disability_Type', models.CharField(blank=True, max_length=100)),
                ('Financial_Concerns', models.CharField(max_length=100)),
                ('Career_Interests', models.TextField()),
                ('Future_Plans', models.TextField()),
            ],
        ),
    ]
